### ISSUE TITLE
[Bug] FishSell can't work on 1.18+

### ISSUE THREAD

**Issue by SnivyJ** [Nobodyno-boop/fixnoOnefishing#12]
i put the FishSell-1.3.Jar in plugins folder and set -javaagent:plugins/FishSell-1.3.jar in start
the/fishsell command cant use and the plugins cant load ，the charsh：https://pastebin.ubuntu.com/p/sBXhq4kgXk/
but the HEX colour can display

JAVA:OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
Server:3488-Spigot-b6d12d1-d48f2d1 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
StartupParameter：java -javaagent:FishSell-1.3.jar -Xms2G -Xmx6G -Dfile.encoding=UTF-8 -Djline.terminal=jline.UnsupportedTerminal -jar spigot-1.18.2.jar -nogui
Plugins (6): LuckPerms, Vault, PlaceholderAPI, XConomy, NoOneFishing, NoOneRods
NoOneFishing:NoOneFishing-1.2.0

**Comment by Nobodyno-boop** [comment]
Hi, i will take a look quickly as posible !

**Comment by Nobodyno-boop** [comment]
Currently fixing on the v1.3.1 will be available soon !
