### ISSUE TITLE
[Question] Can you upadte 1.4 to support 1.19 version

### ISSUE THREAD

**Issue by MineSunshineone** [Nobodyno-boop/fixnoOnefishing#14]

**Comment by Nobodyno-boop** [comment]
did you mean NoOneFishing or the fix?

**Comment by MineSunshineone** [comment]
the fix

**Comment by MineSunshineone** [comment]
update the fix to let noonefishing support 1.19

**Comment by Nobodyno-boop** [comment]
Will be planned to be release on the 30 June, actually for some reason we have a bug.
 i actually fix it and will be availabe soon as posible or the 30 June.

**Comment by Nobodyno-boop** [comment]
Alright, i have currently make available the pre-release to test. 

Feel free to try https://github.com/Nobodyno-boop/fixnoOnefishing/releases/tag/v1.3.1

**Comment by Nobodyno-boop** [comment]
> i will try it and talk to you

Sure
